fail_on_violations: true
ruby:
  enabled: true
  config_file: .rubocop.yml
eslint:
  enabled: true
  config_file: .eslintrc.yml
scss:
  enabled: true
  config_file: .scss-lint.yml
jshint:
  enabled: false
rubocop:
  version: 0.75.0
