require:
  - rubocop-rails
  - standard

inherit_gem:
  standard:
    - config/ruby-3.0.yml

AllCops:
  TargetRailsVersion: 6.0
  NewCops: enable
  Exclude:
    - "bin/**/*"
    - "db/schema.rb"
    - "script/**/*"
    - "tmp/**/*"
    - "uploads/**/*"
    - "vendor/**/*"
    - "**/*.erb"


Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true

Metrics/AbcSize:
  Max: 35

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - lib/**/*.rake
    - spec/**/*
    - config/routes.rb
    - config/initializers/simple_form_bootstrap.rb

Layout/LineLength:
  Enabled: true
  Max: 110

Metrics/MethodLength:
  Enabled: true
  Max: 15
  Exclude:
    - db/migrate/*.rb

# We rely on foreign key constraints to raise errors in some cases, instead
# of using restrict_with_exception.
Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/NotNullColumn:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Exclude:
    - "app/controllers/**/*"
    - "app/decorators/**/*"
    - "app/helpers/**/*"
    - "app/policies/**/*"
    - "app/serializers/**/*"
    - "db/migrate/*.rb"

Style/EmptyMethod:
  EnforcedStyle: expanded

# Sometimes using a series of if/unless blocks in parallel structure is good for readability.
Style/GuardClause:
  Enabled: false

Bundler:
  Enabled: true

Rails:
  Enabled: true
