url:
  host: gather.localhost.tv
  protocol: http
  port: 31337

oauth:
  google:
    client_id: 8047175263225-j9942fn33blvb1o7hg7pq9rv778g3blb.apps.googleusercontent.com
    client_secret: 7d4fc35d83b1c6edb272e

gdrive:
  auth:
    client_id: 302773344240-el7fiv7rk3re87v1sat9u7ckggd6cu1r.apps.googleusercontent.com
    client_secret: xxx
    api_key: xxx


secret_key_base: 64a09c05e3fcbc96c7d4fc35d83b1c6edb272e1ab7232c8f6332d560652409d49216c7a7025ca6e696111d394c731c3a0da144c984280da873c86fff75f47222

email:
  from: Gather <gather@gather.localhost.tv>
  no_reply: No-Reply <noreply@gather.localhost.tv>
  webmaster: someone@example.com
